In [2]:
import numpy as np
np.__version__


'1.15.1'

In [3]:
list1 = [1,2,3,4]
data = np.array(list1)
data

array([1, 2, 3, 4])

In [4]:
type(data)

numpy.ndarray

In [5]:
data.dtype

dtype('int64')

In [6]:
data

array([1, 2, 3, 4])

In [7]:
data[0] = 3.14159
data

array([3, 2, 3, 4])

In [8]:
data2 = np.array([1.2,2,3,4,])
print(data2)
print(data2.dtype)

[1.2 2.  3.  4. ]
float64


In [9]:
data3 = np.array(['string'])

In [10]:
?np


Type:        module
String form: <module 'numpy' from '/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        /anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <http://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <http://ipython.scipy.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 

In [ ]:
pandas introduction notes
    -